title:              Zdeněk David
email:              zdenek.david@educanet.cz
description:        CTU FEE Open Informatics student
author:             Zdeněk David
baseurl:            ""
url:                "https://zdenduk.github.io"

# Social Profiles
twitter_username:
github_username:
facebook_username:
instagram_username:  
linkedin_username: zdenekdavid

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge
